import type { RawNewsSignal } from "@/lib/intelligence-engine";

export const demoSignals: RawNewsSignal[] = [
  {
    id: "signal-1",
    title: "New direct flights between Bucharest and an Asian hub announced",
    summary: "The airline will launch a new direct route from Bucharest, improving access for Romanian travellers.",
    source: "Airline Newsroom",
    sourceKind: "airline",
    country: "România",
    url: "https://example.com/route",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "signal-2",
    title: "European travellers face updated entry requirements from September",
    summary: "The immigration authority published updated entry and visa rules for EU citizens.",
    source: "Immigration Authority",
    sourceKind: "authority",
    country: "Asia",
    url: "https://example.com/entry",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "signal-3",
    title: "European travellers face updated entry requirements from September",
    summary: "A travel publication reports the same immigration change for EU citizens.",
    source: "Travel Publication",
    sourceKind: "publication",
    country: "Asia",
    url: "https://example.com/duplicate-entry",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "signal-4",
    title: "Airport opens a new terminal and changes passenger screening",
    summary: "Passengers are advised to arrive earlier during the transition period.",
    source: "Airport Media Centre",
    sourceKind: "airport",
    country: "Europa",
    url: "https://example.com/terminal",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "signal-5",
    title: "Tourist tax increases for international visitors",
    summary: "The national tourism authority confirmed a higher tourist levy from next season.",
    source: "Tourism Authority",
    sourceKind: "tourism",
    country: "Europa",
    url: "https://example.com/tax",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "signal-6",
    title: "Airline changes cabin baggage dimensions on low-cost fares",
    summary: "The new carry-on limits apply to tickets purchased after the announced date.",
    source: "Airline Newsroom",
    sourceKind: "airline",
    country: "Global",
    url: "https://example.com/baggage",
    publishedAt: new Date().toISOString(),
  },
];
