export type SourceKind = "airline" | "airport" | "tourism" | "authority" | "publication";
export type SourceMethod = "rss" | "web" | "api";

export type TravelSource = {
  id: string;
  name: string;
  country: string;
  kind: SourceKind;
  method: SourceMethod;
  url: string;
  feedUrl?: string;
  active: boolean;
  frequencyMinutes: number;
};

const source = (
  id: string,
  name: string,
  country: string,
  kind: SourceKind,
  url: string,
  frequencyMinutes = 60,
  method: SourceMethod = "web"
): TravelSource => ({ id, name, country, kind, method, url, active: true, frequencyMinutes });

export const initialSources: TravelSource[] = [
  // Autorități și organizații internaționale
  source("iata-news", "IATA News", "Global", "authority", "https://www.iata.org/en/pressroom/"),
  source("icao", "ICAO Newsroom", "Global", "authority", "https://www.icao.int/Newsroom/Pages/default.aspx"),
  source("easa-news", "EASA Newsroom", "Europa", "authority", "https://www.easa.europa.eu/en/newsroom-and-events"),
  source("faa", "FAA Newsroom", "SUA", "authority", "https://www.faa.gov/newsroom"),
  source("ec-mobility", "European Commission Mobility", "Uniunea Europeană", "authority", "https://transport.ec.europa.eu/news-events/news_en"),
  source("ec-migration", "European Commission Migration and Home Affairs", "Uniunea Europeană", "authority", "https://home-affairs.ec.europa.eu/news_en"),
  source("eu-consilium", "Council of the European Union – Press", "Uniunea Europeană", "authority", "https://www.consilium.europa.eu/en/press/press-releases/"),
  source("frontex", "Frontex News", "Uniunea Europeană", "authority", "https://www.frontex.europa.eu/media-centre/news/"),
  source("eurocontrol", "EUROCONTROL News", "Europa", "authority", "https://www.eurocontrol.int/news"),
  source("tsa", "TSA News", "SUA", "authority", "https://www.tsa.gov/news/press/releases"),
  source("cbp", "US Customs and Border Protection", "SUA", "authority", "https://www.cbp.gov/newsroom"),
  source("uk-home-office", "UK Home Office News", "Regatul Unit", "authority", "https://www.gov.uk/government/organisations/home-office"),
  source("uk-fco", "UK Foreign, Commonwealth & Development Office", "Regatul Unit", "authority", "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office"),
  source("australia-home-affairs", "Australia Department of Home Affairs", "Australia", "authority", "https://www.homeaffairs.gov.au/news-media"),
  source("canada-ircc", "Immigration, Refugees and Citizenship Canada", "Canada", "authority", "https://www.canada.ca/en/immigration-refugees-citizenship/news.html"),
  source("japan-mofa", "Japan Ministry of Foreign Affairs", "Japonia", "authority", "https://www.mofa.go.jp/press/index.html"),
  source("singapore-ica", "Singapore Immigration & Checkpoints Authority", "Singapore", "authority", "https://www.ica.gov.sg/news-and-publications/newsroom"),
  source("thailand-mfa", "Thailand Ministry of Foreign Affairs", "Thailanda", "authority", "https://www.mfa.go.th/en/index"),
  source("vietnam-immigration", "Vietnam Immigration Department", "Vietnam", "authority", "https://evisa.gov.vn/"),
  source("who-news", "World Health Organization News", "Global", "authority", "https://www.who.int/news"),

  // Companii aeriene
  source("singapore-airlines", "Singapore Airlines Newsroom", "Singapore", "airline", "https://www.singaporeair.com/en_UK/us/media-centre/"),
  source("emirates", "Emirates Media Centre", "Emiratele Arabe Unite", "airline", "https://www.emirates.com/media-centre/"),
  source("qatar-airways", "Qatar Airways Press Releases", "Qatar", "airline", "https://www.qatarairways.com/press-releases/en-WW/"),
  source("etihad", "Etihad Airways News", "Emiratele Arabe Unite", "airline", "https://www.etihad.com/en/news"),
  source("turkish-airlines", "Turkish Airlines Press Room", "Turcia", "airline", "https://www.turkishairlines.com/en-int/press-room/"),
  source("lufthansa", "Lufthansa Group Newsroom", "Germania", "airline", "https://newsroom.lufthansagroup.com/en/"),
  source("air-france", "Air France Corporate News", "Franța", "airline", "https://corporate.airfrance.com/en/news"),
  source("klm", "KLM Newsroom", "Țările de Jos", "airline", "https://news.klm.com/"),
  source("british-airways", "British Airways Media Centre", "Regatul Unit", "airline", "https://mediacentre.britishairways.com/"),
  source("iberia", "Iberia Newsroom", "Spania", "airline", "https://grupo.iberia.com/newsroom/"),
  source("tap", "TAP Air Portugal News", "Portugalia", "airline", "https://www.tapairportugal.com/en/media"),
  source("swiss", "SWISS Media Relations", "Elveția", "airline", "https://www.swiss.com/corporate/en/media"),
  source("austrian", "Austrian Airlines Media", "Austria", "airline", "https://www.austrianairlines.ag/en/press/"),
  source("sas", "SAS Newsroom", "Scandinavia", "airline", "https://www.sasgroup.net/newsroom/"),
  source("finnair", "Finnair Newsroom", "Finlanda", "airline", "https://company.finnair.com/en/media"),
  source("lot", "LOT Polish Airlines News", "Polonia", "airline", "https://www.lot.com/ro/en/explore/about-lot/press-room"),
  source("aer-lingus", "Aer Lingus Media Centre", "Irlanda", "airline", "https://mediacentre.aerlingus.com/"),
  source("ryanair", "Ryanair News", "Irlanda", "airline", "https://corporate.ryanair.com/news/"),
  source("easyjet", "easyJet Media Centre", "Regatul Unit", "airline", "https://www.easyjet.com/en/newsroom"),
  source("wizz-air", "Wizz Air Newsroom", "Ungaria", "airline", "https://wizzair.com/en-gb/information-and-services/about-us/news"),
  source("norwegian", "Norwegian Newsroom", "Norvegia", "airline", "https://media.uk.norwegian.com/"),
  source("airbaltic", "airBaltic Newsroom", "Letonia", "airline", "https://www.airbaltic.com/en/airbaltic-news"),
  source("aegean", "Aegean Airlines Press Releases", "Grecia", "airline", "https://en.about.aegeanair.com/media-center/press-releases/"),
  source("ita-airways", "ITA Airways Press Releases", "Italia", "airline", "https://www.ita-airways.com/en_en/fly-ita/ita-world/press-releases.html"),
  source("air-canada", "Air Canada Media", "Canada", "airline", "https://media.aircanada.com/"),
  source("american-airlines", "American Airlines Newsroom", "SUA", "airline", "https://news.aa.com/"),
  source("delta", "Delta News Hub", "SUA", "airline", "https://news.delta.com/"),
  source("united", "United Airlines Newsroom", "SUA", "airline", "https://www.united.com/en/us/newsroom"),
  source("southwest", "Southwest Airlines Newsroom", "SUA", "airline", "https://www.swamedia.com/"),
  source("alaska-airlines", "Alaska Airlines Newsroom", "SUA", "airline", "https://newsroom.alaskaair.com/"),
  source("jetblue", "JetBlue Newsroom", "SUA", "airline", "https://news.jetblue.com/"),
  source("ana", "ANA Group News", "Japonia", "airline", "https://www.anahd.co.jp/group/en/pr/"),
  source("japan-airlines", "Japan Airlines Press Releases", "Japonia", "airline", "https://press.jal.co.jp/en/"),
  source("cathay-pacific", "Cathay Pacific News", "Hong Kong", "airline", "https://news.cathaypacific.com/"),
  source("air-china", "Air China News", "China", "airline", "https://www.airchina.com.cn/en/investor_relations/"),
  source("china-eastern", "China Eastern News", "China", "airline", "https://global.ceair.com/global/static/Announcement/"),
  source("china-southern", "China Southern News", "China", "airline", "https://www.csair.com/en/about/news/"),
  source("korean-air", "Korean Air Newsroom", "Coreea de Sud", "airline", "https://newsroom.koreanair.com/"),
  source("asiana", "Asiana Airlines News", "Coreea de Sud", "airline", "https://flyasiana.com/C/US/EN/company/news-room"),
  source("thai-airways", "Thai Airways News", "Thailanda", "airline", "https://www.thaiairways.com/en_TH/news/news_announcement.page"),
  source("vietnam-airlines", "Vietnam Airlines News", "Vietnam", "airline", "https://www.vietnamairlines.com/en/news"),
  source("airasia", "AirAsia Newsroom", "Malaysia", "airline", "https://newsroom.airasia.com/"),
  source("malaysia-airlines", "Malaysia Airlines News", "Malaysia", "airline", "https://www.malaysiaairlines.com/my/en/news-article.html"),
  source("garuda", "Garuda Indonesia News", "Indonezia", "airline", "https://www.garuda-indonesia.com/id/en/news-and-events"),
  source("qantas", "Qantas Newsroom", "Australia", "airline", "https://www.qantasnewsroom.com.au/"),
  source("air-new-zealand", "Air New Zealand Media Releases", "Noua Zeelandă", "airline", "https://www.airnewzealandnewsroom.com/"),

  // Aeroporturi
  source("heathrow", "Heathrow Media Centre", "Regatul Unit", "airport", "https://mediacentre.heathrow.com/"),
  source("gatwick", "Gatwick Media Centre", "Regatul Unit", "airport", "https://www.mediacentre.gatwickairport.com/"),
  source("stansted", "London Stansted Media Centre", "Regatul Unit", "airport", "https://mediacentre.stanstedairport.com/"),
  source("schiphol", "Schiphol Newsroom", "Țările de Jos", "airport", "https://news.schiphol.com/"),
  source("frankfurt-airport", "Frankfurt Airport Newsroom", "Germania", "airport", "https://www.fraport.com/en/newsroom.html"),
  source("munich-airport", "Munich Airport Press", "Germania", "airport", "https://www.munich-airport.com/press-263141"),
  source("paris-airports", "Groupe ADP News", "Franța", "airport", "https://www.parisaeroport.fr/en/group/group-strategy/news"),
  source("madrid-airport", "Aena News", "Spania", "airport", "https://www.aena.es/en/press.html"),
  source("barcelona-airport", "Aena Barcelona News", "Spania", "airport", "https://www.aena.es/en/josep-tarradellas-barcelona-el-prat.html"),
  source("rome-airports", "Aeroporti di Roma News", "Italia", "airport", "https://www.adr.it/web/aeroporti-di-roma-en/news"),
  source("vienna-airport", "Vienna Airport Press", "Austria", "airport", "https://www.viennaairport.com/en/company/press"),
  source("zurich-airport", "Zurich Airport News", "Elveția", "airport", "https://www.flughafen-zuerich.ch/en/company/media/news"),
  source("copenhagen-airport", "Copenhagen Airport News", "Danemarca", "airport", "https://www.cph.dk/en/about-cph/press/news"),
  source("oslo-airport", "Avinor News", "Norvegia", "airport", "https://avinor.no/en/corporate/about-us/news/"),
  source("helsinki-airport", "Finavia Newsroom", "Finlanda", "airport", "https://www.finavia.fi/en/newsroom"),
  source("warsaw-airport", "Warsaw Chopin Airport News", "Polonia", "airport", "https://www.lotnisko-chopina.pl/en/news.html"),
  source("prague-airport", "Prague Airport News", "Cehia", "airport", "https://www.prg.aero/en/news"),
  source("budapest-airport", "Budapest Airport News", "Ungaria", "airport", "https://www.bud.hu/en/budapest_airport/media/news"),
  source("athens-airport", "Athens International Airport Press", "Grecia", "airport", "https://www.aia.gr/company-and-business/press-and-media/press-releases"),
  source("istanbul-airport", "İGA Istanbul Airport News", "Turcia", "airport", "https://www.istairport.com/en/announcements/"),
  source("dubai-airports", "Dubai Airports Media Centre", "Emiratele Arabe Unite", "airport", "https://media.dubaiairports.ae/"),
  source("doha-airport", "Hamad International Airport News", "Qatar", "airport", "https://dohahamadairport.com/press-releases"),
  source("singapore-changi", "Changi Airport Newsroom", "Singapore", "airport", "https://www.changiairport.com/corporate/media-centre.html"),
  source("hong-kong-airport", "Hong Kong International Airport Media Centre", "Hong Kong", "airport", "https://www.hongkongairport.com/en/media-centre/press-release/"),
  source("incheon-airport", "Incheon Airport News", "Coreea de Sud", "airport", "https://www.airport.kr/co/en/cmm/cmmBbsList.do?FNCT_CODE=121"),
  source("narita-airport", "Narita Airport News", "Japonia", "airport", "https://www.narita-airport.jp/en/company/press/"),
  source("haneda-airport", "Haneda Airport News", "Japonia", "airport", "https://tokyo-haneda.com/en/information/"),
  source("bangkok-airports", "Airports of Thailand News", "Thailanda", "airport", "https://www.airportthai.co.th/en/category/news/"),
  source("kuala-lumpur-airport", "Malaysia Airports News", "Malaysia", "airport", "https://www.malaysiaairports.com.my/media-centre"),
  source("sydney-airport", "Sydney Airport Media", "Australia", "airport", "https://www.sydneyairport.com.au/corporate/media/corporate-newsroom"),
  source("melbourne-airport", "Melbourne Airport Newsroom", "Australia", "airport", "https://www.melbourneairport.com.au/corporate/newsroom"),
  source("jfk-lga-ewr", "Port Authority Airports News", "SUA", "airport", "https://www.panynj.gov/port-authority/en/press-room.html"),
  source("lax", "Los Angeles World Airports News", "SUA", "airport", "https://www.lawa.org/news-releases"),
  source("san-francisco-airport", "San Francisco Airport News", "SUA", "airport", "https://www.flysfo.com/about/media/press-releases"),
  source("atlanta-airport", "Atlanta Airport News", "SUA", "airport", "https://www.atl.com/media-center/"),
  source("toronto-airport", "Toronto Pearson News", "Canada", "airport", "https://www.torontopearson.com/en/corporate/media"),
  source("vancouver-airport", "Vancouver Airport News", "Canada", "airport", "https://www.yvr.ca/en/media/news-releases"),

  // Organizații naționale de turism
  source("japan-tourism", "Japan National Tourism Organization", "Japonia", "tourism", "https://www.japan.travel/en/news/", 120),
  source("thailand-tourism", "Tourism Authority of Thailand", "Thailanda", "tourism", "https://www.tatnews.org/", 120),
  source("travel-europe", "European Travel Commission", "Europa", "tourism", "https://etc-corporate.org/news/", 120),
  source("un-tourism", "UN Tourism News", "Global", "tourism", "https://www.unwto.org/news", 120),
  source("visit-britain", "VisitBritain Media Centre", "Regatul Unit", "tourism", "https://www.visitbritain.org/media-centre", 120),
  source("france-tourism", "Atout France News", "Franța", "tourism", "https://www.atout-france.fr/en/news", 120),
  source("germany-tourism", "German National Tourist Board", "Germania", "tourism", "https://www.germany.travel/en/newsroom.html", 120),
  source("spain-tourism", "Turespaña News", "Spania", "tourism", "https://www.tourspain.es/en-us/", 120),
  source("italy-tourism", "Italia.it News", "Italia", "tourism", "https://www.italia.it/en/news", 120),
  source("portugal-tourism", "Turismo de Portugal", "Portugalia", "tourism", "https://www.turismodeportugal.pt/en/Pages/homepage.aspx", 120),
  source("greece-tourism", "Greek National Tourism Organisation", "Grecia", "tourism", "https://www.visitgreece.gr/", 120),
  source("croatia-tourism", "Croatian National Tourist Board", "Croația", "tourism", "https://www.htz.hr/en-GB/press", 120),
  source("turkey-tourism", "GoTürkiye News", "Turcia", "tourism", "https://goturkiye.com/", 120),
  source("dubai-tourism", "Dubai Department of Economy and Tourism", "Dubai", "tourism", "https://www.dubaidet.gov.ae/en/newsroom", 120),
  source("abu-dhabi-tourism", "Department of Culture and Tourism Abu Dhabi", "Abu Dhabi", "tourism", "https://dct.gov.ae/en/media.centre/news.aspx", 120),
  source("qatar-tourism", "Qatar Tourism News", "Qatar", "tourism", "https://www.qatartourism.com/en/news-and-media", 120),
  source("singapore-tourism", "Singapore Tourism Board", "Singapore", "tourism", "https://www.stb.gov.sg/content/stb/en/media-centre/media-releases.html", 120),
  source("malaysia-tourism", "Tourism Malaysia News", "Malaysia", "tourism", "https://www.tourism.gov.my/media"),
  source("indonesia-tourism", "Wonderful Indonesia", "Indonezia", "tourism", "https://www.indonesia.travel/gb/en/news/", 120),
  source("vietnam-tourism", "Vietnam National Authority of Tourism", "Vietnam", "tourism", "https://vietnamtourism.gov.vn/en", 120),
  source("philippines-tourism", "Philippines Department of Tourism", "Filipine", "tourism", "https://beta.tourism.gov.ph/news-and-updates/", 120),
  source("korea-tourism", "Korea Tourism Organization", "Coreea de Sud", "tourism", "https://kto.visitkorea.or.kr/eng/", 120),
  source("china-tourism", "China Ministry of Culture and Tourism", "China", "tourism", "https://en.mct.gov.cn/", 120),
  source("australia-tourism", "Tourism Australia Media", "Australia", "tourism", "https://www.tourism.australia.com/en/news-and-media.html", 120),
  source("new-zealand-tourism", "Tourism New Zealand Media", "Noua Zeelandă", "tourism", "https://www.tourismnewzealand.com/news/", 120),
  source("canada-tourism", "Destination Canada News", "Canada", "tourism", "https://www.destinationcanada.com/en/news", 120),
  source("usa-tourism", "Brand USA Newsroom", "SUA", "tourism", "https://www.thebrandusa.com/media/newsroom", 120),
  source("mexico-tourism", "Visit Mexico", "Mexic", "tourism", "https://visitmexico.com/", 120),
  source("south-africa-tourism", "South African Tourism", "Africa de Sud", "tourism", "https://www.southafrica.net/gl/en/corporate/press", 120),
  source("morocco-tourism", "Morocco National Tourism Office", "Maroc", "tourism", "https://www.visitmorocco.com/en", 120),

  // Publicații și fluxuri profesionale
  source("travel-weekly", "Travel Weekly", "Global", "publication", "https://www.travelweekly.com/", 60),
  source("skift", "Skift", "Global", "publication", "https://skift.com/", 60),
  source("phocuswire", "PhocusWire", "Global", "publication", "https://www.phocuswire.com/", 60),
  source("simple-flying", "Simple Flying", "Global", "publication", "https://simpleflying.com/", 60),
  source("aerotime", "AeroTime", "Global", "publication", "https://www.aerotime.aero/", 60),
  source("routes-online", "Routes Online", "Global", "publication", "https://www.routesonline.com/news/", 60),
  source("airport-world", "Airport World", "Global", "publication", "https://airport-world.com/", 60),
  source("business-travel-news", "Business Travel News", "Global", "publication", "https://www.businesstravelnews.com/", 60),
  source("travel-mole", "TravelMole", "Global", "publication", "https://www.travelmole.com/", 60),
  source("travel-daily-media", "Travel Daily Media", "Global", "publication", "https://www.traveldailymedia.com/", 60),
  source("breaking-travel-news", "Breaking Travel News", "Global", "publication", "https://www.breakingtravelnews.com/", 60),
  source("travel-and-tour-world", "Travel And Tour World", "Global", "publication", "https://www.travelandtourworld.com/", 60),
  source("the-points-guy", "The Points Guy", "SUA", "publication", "https://thepointsguy.com/news/", 60),
  source("lonely-planet-news", "Lonely Planet News", "Global", "publication", "https://www.lonelyplanet.com/news", 60),
  source("cn-traveler", "Condé Nast Traveler", "Global", "publication", "https://www.cntraveler.com/", 60)
];
